networks:
  my_network:
    driver: bridge
services:
  mysql:
    networks:
      - my_network
    image: mysql:8.0.30
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  rabbitmq:
    networks:
      - my_network
    image: rabbitmq:3.12.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
  redis:
    networks:
      - my_network
    image: redis:7.0.8
    container_name: redis
    ports:
      - "6379:6379"
  nacos:
    networks:
      - my_network
    image: nacos/nacos-server:v2.2.3
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname
      SPRING_DATASOURCE_PLATFORM: derby